name: vendor_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

   # State management
  provider: ^6.1.2
  image_picker: ^1.1.2
  geolocator: ^12.0.0  # or latest
  geocoding: ^3.0.0
  # Networking
  dio: ^5.7.0
  # Secure token storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
    # UI utils (same as yours)
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Onest
      fonts:
         - asset: assets/fonts/Onest-Black.ttf
           weight: 700
    - family: OnestBold
      fonts:
         - asset: assets/fonts/Onest-Bold.ttf
           weight: 700
    - family: OnestExtraBold
      fonts:
         - asset: assets/fonts/Onest-ExtraBold.ttf
           weight: 800
    - family: OnestExtraLight
      fonts:
         - asset: assets/fonts/Onest-ExtraLight.ttf
           weight: 100
    - family: OnestLight
      fonts:
         - asset: assets/fonts/Onest-Light.ttf
           weight: 300
    - family: OnestMedium
      fonts:
         - asset: assets/fonts/Onest-Medium.ttf
           weight: 500
    - family: OnestRegular
      fonts:
         - asset: assets/fonts/Onest-Regular.ttf
           weight: 400
    - family: OnestSemiBold
      fonts:
         - asset: assets/fonts/Onest-SemiBold.ttf
           weight: 600
    - family: OnestThin
      fonts:
         - asset: assets/fonts/Onest-Thin.ttf
           weight: 200

